version: '4.3'
services:
  wordpress:
    image: wordpress
    ports:
      - 8080:80
    enviroment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: bloguser
      WORDPRESS_DB_PASSWORD: test123,
      WORDPRESS_DB_NAME: blogdb
    volumes: -wordpress:/var/www/html

  db:
    image: mysql:5.3
    restart: always
    enviroment:
      MYSQL_DATABASE: blogdb
      MYSQL_USER: bloguser
      MYSQL_PASSWORD: test123
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes: -db:/var/lib/mysql
  volumes:
    wordpress:
    db:


